version: '3.3'

services:
  db:
    image: postgres:9.3
    environment:
      POSTGRES_DB: db_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password


  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./dev.env
