# Generated by Django 2.1.3 on 2018-11-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('SKU', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Штрих код')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новинка')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка товара')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True, verbose_name='Дата провередения операции')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('action', models.CharField(choices=[('A', 'add'), ('R', 'remove')], max_length=1, verbose_name='Операция')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog_api.Product', verbose_name='Продукт')),
            ],
        ),
    ]
