# Generated by Django 2.1.3 on 2018-11-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка товара'),
        ),
    ]
